### ISSUE TITLE
The transient name never includes the menu name

### ISSUE THREAD

**Issue by grappler** [Rarst/fragment-cache#10]
I am using Fragment Cache with Polylang a multilingual plugin. The problem that I realized is that Fragment Cache loads the same menu regardless of language for the same menu location.

The reason is that this line of code does not work or better said `$args['menu']` always returns an empty string.
`$name = is_object( $args['menu'] ) ? $args['menu']->slug : $args['menu'];`

The reason is that if `menu` is not defined as an argument in the theme template it will be an empty string. The `menu` argument is only defined after `pre_wp_nav_menu`

https://developer.wordpress.org/reference/functions/wp_nav_menu/

**Comment by Rarst** [comment]
Sorry this took a while to get to, wasn't active on code things for a while.

I don't quite follow. If you don't give `wp_nav_menu()` a _specific_ menu to produce (by name or location) it will just figure something out and will throw _some_ menu your way. Fragment Cache just passes input to core here.

> The reason is that if menu is not defined as an argument in the theme template

It this bit specific to Polylang here? How exactly is name of the menu chosen / modified?

**Comment by Rarst** [comment]
We went over this issue in person and the reason is following: theme uses `theme_location` to call `wp_nav_menu()`, but another plugin changes menu choice _depending on context_ dynamically. This isn't something WP core ever does natively, so it is hard to account for.

My first take for such scenario would be to use `wp_nav_menu_args` filter to resolve `theme_location` into `menu` early and change input arguments accordingly. That way Fragment Cache would treat and cache two menus as two different calls, rather than single theme location one.

**Comment by lkraav** [comment]
> We went over this issue in person and the reason is following: theme uses theme_location to call wp_nav_menu(), but another plugin changes menu choice depending on context dynamically. This isn't something WP core ever does natively, so it is hard to account for.

I also chose to do this: it's clean, simple, and works. In comparison, definining tens of theme locations doesn't seem better.

**Comment by Rarst** [comment]
I don't disagree, but in context of Fragment Cache it matters _how_ you do the overwrite. If the _same_ `wp_nav_menu()` arguments can result in _different_ menus — that is not something that can be detected by the plugin.

As above — it should just work if input arguments are adjusted so that menus can be disambiguated.

**Comment by grappler** [comment]
This the coded that I added to fix the issue.

```php
/**
 * Cache menus instead of location for multilingual sites.
 */
add_filter( 'wp_nav_menu_args', function( $args ) {
	// Check if Polylang is installed.
	if ( function_exists( 'pll' ) ) {
		// Define the menu object before `pre_wp_nav_menu` to cache menus instead of locations.
		if ( ! $args['menu'] && $args['theme_location'] && ( $locations = get_nav_menu_locations() ) && isset( $locations[ $args['theme_location'] ] ) ) {
			$args['menu'] = wp_get_nav_menu_object( $locations[ $args['theme_location'] ] );
		}
	}
	return $args;
} );
```
